### ISSUE TITLE
App Crashes when time < time at place

### ISSUE THREAD

**Issue by kermitnirmit** [whereToApplication/whereTo#36]
Example, 

- if you pick a time 10 min from now, then pick fast for the pace, itll crash

- if you don't change the time, it'll crash

- if you pick a time 50 min from now, then pick slow, it'll crash

- and so on

**Another recreation** - 1 hour, any preference, medium == crash!!!!!!

**and another one!** - Open the app and hit pace == crash!!!!!!!!!! (Set a default time to 1 hour)

**and another one!** - 2 hour + any preference + slow = CRASh!!!!!!!!!!!!!!
 
**I WILL FIND YOU AND I WILL CRASH YOU**

**Comment by krrishdholakia** [comment]
bug fixes pushed
