### ISSUE TITLE
/feedback route not posting data to backend 

### ISSUE THREAD

**Issue by ghost** [whereToApplication/whereTo#52]
Feedback route not posting data correctly to backend. object is being created but the feedback is not being stored there.

**Comment by ghost** [comment]
<img width="346" alt="screen shot 2018-11-13 at 1 54 42 am" src="https://user-images.githubusercontent.com/17561003/48396035-2527cf80-e6e7-11e8-9eda-33e777908009.png">

**Comment by ghost** [comment]
Tried to debug the problem but couldn't get the process.env.MONGODB_URI variable. 

@thejameswang could you share the heroku credentials?

**Comment by thejameswang** [comment]
To create a post request with Postman. Send data through Body using Raw in a JSON format like, 
{ 
    "feedback": "This is a test feedback"
}

Also, remember to make Headers: content-type to be application/JSON
