### ISSUE TITLE
UserPreferenceViewController Unresponsive Screen - iOS

### ISSUE THREAD

**Issue by thejameswang** [whereToApplication/whereTo#71]
Currently, choosing on the screen is poor. It is non-responsive, and liking, disliking, occasionally.

**Comment by thejameswang** [comment]
In progess, finished background change visual cues for like and dislike. Problem: Random background color selection for bottom cells

**Comment by ghost** [comment]
done.

**Comment by ghost** [comment]
for future reference: used tableView.reloadData() function in the thumbsUp thumbsDown gestures
